import colors from 'colors-named';
import names from '../';

it('=> names.length', () => expect(names.length).toBe(148));

it('=> includes #F0F8FF', () => expect(names.includes('#F0F8FF')).toBeTruthy());
it('=> includes #FAEBD7', () => expect(names.includes('#FAEBD7')).toBeTruthy());
it('=> includes #00FFFF', () => expect(names.includes('#00FFFF')).toBeTruthy());
it('=> includes #7FFFD4', () => expect(names.includes('#7FFFD4')).toBeTruthy());
it('=> includes #F0FFFF', () => expect(names.includes('#F0FFFF')).toBeTruthy());
it('=> includes #F5F5DC', () => expect(names.includes('#F5F5DC')).toBeTruthy());
it('=> includes #FFE4C4', () => expect(names.includes('#FFE4C4')).toBeTruthy());
it('=> includes #000000', () => expect(names.includes('#000000')).toBeTruthy());
it('=> includes #FFEBCD', () => expect(names.includes('#FFEBCD')).toBeTruthy());
it('=> includes #0000FF', () => expect(names.includes('#0000FF')).toBeTruthy());
it('=> includes #8A2BE2', () => expect(names.includes('#8A2BE2')).toBeTruthy());
it('=> includes #A52A2A', () => expect(names.includes('#A52A2A')).toBeTruthy());
it('=> includes #DEB887', () => expect(names.includes('#DEB887')).toBeTruthy());
it('=> includes #5F9EA0', () => expect(names.includes('#5F9EA0')).toBeTruthy());
it('=> includes #7FFF00', () => expect(names.includes('#7FFF00')).toBeTruthy());
it('=> includes #D2691E', () => expect(names.includes('#D2691E')).toBeTruthy());
it('=> includes #FF7F50', () => expect(names.includes('#FF7F50')).toBeTruthy());
it('=> includes #6495ED', () => expect(names.includes('#6495ED')).toBeTruthy());
it('=> includes #FFF8DC', () => expect(names.includes('#FFF8DC')).toBeTruthy());
it('=> includes #DC143C', () => expect(names.includes('#DC143C')).toBeTruthy());
it('=> includes #00FFFF', () => expect(names.includes('#00FFFF')).toBeTruthy());
it('=> includes #00008B', () => expect(names.includes('#00008B')).toBeTruthy());
it('=> includes #008B8B', () => expect(names.includes('#008B8B')).toBeTruthy());
it('=> includes #B8860B', () => expect(names.includes('#B8860B')).toBeTruthy());
it('=> includes #A9A9A9', () => expect(names.includes('#A9A9A9')).toBeTruthy());
it('=> includes #006400', () => expect(names.includes('#006400')).toBeTruthy());
it('=> includes #A9A9A9', () => expect(names.includes('#A9A9A9')).toBeTruthy());
it('=> includes #BDB76B', () => expect(names.includes('#BDB76B')).toBeTruthy());
it('=> includes #8B008B', () => expect(names.includes('#8B008B')).toBeTruthy());
it('=> includes #556B2F', () => expect(names.includes('#556B2F')).toBeTruthy());
it('=> includes #FF8C00', () => expect(names.includes('#FF8C00')).toBeTruthy());
it('=> includes #9932CC', () => expect(names.includes('#9932CC')).toBeTruthy());
it('=> includes #8B0000', () => expect(names.includes('#8B0000')).toBeTruthy());
it('=> includes #E9967A', () => expect(names.includes('#E9967A')).toBeTruthy());
it('=> includes #8FBC8F', () => expect(names.includes('#8FBC8F')).toBeTruthy());
it('=> includes #483D8B', () => expect(names.includes('#483D8B')).toBeTruthy());
it('=> includes #2F4F4F', () => expect(names.includes('#2F4F4F')).toBeTruthy());
it('=> includes #2F4F4F', () => expect(names.includes('#2F4F4F')).toBeTruthy());
it('=> includes #00CED1', () => expect(names.includes('#00CED1')).toBeTruthy());
it('=> includes #9400D3', () => expect(names.includes('#9400D3')).toBeTruthy());
it('=> includes #FF1493', () => expect(names.includes('#FF1493')).toBeTruthy());
it('=> includes #00BFFF', () => expect(names.includes('#00BFFF')).toBeTruthy());
it('=> includes #696969', () => expect(names.includes('#696969')).toBeTruthy());
it('=> includes #696969', () => expect(names.includes('#696969')).toBeTruthy());
it('=> includes #1E90FF', () => expect(names.includes('#1E90FF')).toBeTruthy());
it('=> includes #B22222', () => expect(names.includes('#B22222')).toBeTruthy());
it('=> includes #FFFAF0', () => expect(names.includes('#FFFAF0')).toBeTruthy());
it('=> includes #228B22', () => expect(names.includes('#228B22')).toBeTruthy());
it('=> includes #FF00FF', () => expect(names.includes('#FF00FF')).toBeTruthy());
it('=> includes #DCDCDC', () => expect(names.includes('#DCDCDC')).toBeTruthy());
it('=> includes #F8F8FF', () => expect(names.includes('#F8F8FF')).toBeTruthy());
it('=> includes #FFD700', () => expect(names.includes('#FFD700')).toBeTruthy());
it('=> includes #DAA520', () => expect(names.includes('#DAA520')).toBeTruthy());
it('=> includes #808080', () => expect(names.includes('#808080')).toBeTruthy());
it('=> includes #008000', () => expect(names.includes('#008000')).toBeTruthy());
it('=> includes #ADFF2F', () => expect(names.includes('#ADFF2F')).toBeTruthy());
it('=> includes #808080', () => expect(names.includes('#808080')).toBeTruthy());
it('=> includes #F0FFF0', () => expect(names.includes('#F0FFF0')).toBeTruthy());
it('=> includes #FF69B4', () => expect(names.includes('#FF69B4')).toBeTruthy());
it('=> includes #CD5C5C', () => expect(names.includes('#CD5C5C')).toBeTruthy());
it('=> includes #4B0082', () => expect(names.includes('#4B0082')).toBeTruthy());
it('=> includes #FFFFF0', () => expect(names.includes('#FFFFF0')).toBeTruthy());
it('=> includes #F0E68C', () => expect(names.includes('#F0E68C')).toBeTruthy());
it('=> includes #E6E6FA', () => expect(names.includes('#E6E6FA')).toBeTruthy());
it('=> includes #FFF0F5', () => expect(names.includes('#FFF0F5')).toBeTruthy());
it('=> includes #7CFC00', () => expect(names.includes('#7CFC00')).toBeTruthy());
it('=> includes #FFFACD', () => expect(names.includes('#FFFACD')).toBeTruthy());
it('=> includes #ADD8E6', () => expect(names.includes('#ADD8E6')).toBeTruthy());
it('=> includes #F08080', () => expect(names.includes('#F08080')).toBeTruthy());
it('=> includes #E0FFFF', () => expect(names.includes('#E0FFFF')).toBeTruthy());
it('=> includes #FAFAD2', () => expect(names.includes('#FAFAD2')).toBeTruthy());
it('=> includes #D3D3D3', () => expect(names.includes('#D3D3D3')).toBeTruthy());
it('=> includes #90EE90', () => expect(names.includes('#90EE90')).toBeTruthy());
it('=> includes #D3D3D3', () => expect(names.includes('#D3D3D3')).toBeTruthy());
it('=> includes #FFB6C1', () => expect(names.includes('#FFB6C1')).toBeTruthy());
it('=> includes #FFA07A', () => expect(names.includes('#FFA07A')).toBeTruthy());
it('=> includes #20B2AA', () => expect(names.includes('#20B2AA')).toBeTruthy());
it('=> includes #87CEFA', () => expect(names.includes('#87CEFA')).toBeTruthy());
it('=> includes #778899', () => expect(names.includes('#778899')).toBeTruthy());
it('=> includes #778899', () => expect(names.includes('#778899')).toBeTruthy());
it('=> includes #B0C4DE', () => expect(names.includes('#B0C4DE')).toBeTruthy());
it('=> includes #FFFFE0', () => expect(names.includes('#FFFFE0')).toBeTruthy());
it('=> includes #00FF00', () => expect(names.includes('#00FF00')).toBeTruthy());
it('=> includes #32CD32', () => expect(names.includes('#32CD32')).toBeTruthy());
it('=> includes #FAF0E6', () => expect(names.includes('#FAF0E6')).toBeTruthy());
it('=> includes #FF00FF', () => expect(names.includes('#FF00FF')).toBeTruthy());
it('=> includes #800000', () => expect(names.includes('#800000')).toBeTruthy());
it('=> includes #66CDAA', () => expect(names.includes('#66CDAA')).toBeTruthy());
it('=> includes #0000CD', () => expect(names.includes('#0000CD')).toBeTruthy());
it('=> includes #BA55D3', () => expect(names.includes('#BA55D3')).toBeTruthy());
it('=> includes #9370DB', () => expect(names.includes('#9370DB')).toBeTruthy());
it('=> includes #3CB371', () => expect(names.includes('#3CB371')).toBeTruthy());
it('=> includes #7B68EE', () => expect(names.includes('#7B68EE')).toBeTruthy());
it('=> includes #00FA9A', () => expect(names.includes('#00FA9A')).toBeTruthy());
it('=> includes #48D1CC', () => expect(names.includes('#48D1CC')).toBeTruthy());
it('=> includes #C71585', () => expect(names.includes('#C71585')).toBeTruthy());
it('=> includes #191970', () => expect(names.includes('#191970')).toBeTruthy());
it('=> includes #F5FFFA', () => expect(names.includes('#F5FFFA')).toBeTruthy());
it('=> includes #FFE4E1', () => expect(names.includes('#FFE4E1')).toBeTruthy());
it('=> includes #FFE4B5', () => expect(names.includes('#FFE4B5')).toBeTruthy());
it('=> includes #FFDEAD', () => expect(names.includes('#FFDEAD')).toBeTruthy());
it('=> includes #000080', () => expect(names.includes('#000080')).toBeTruthy());
it('=> includes #FDF5E6', () => expect(names.includes('#FDF5E6')).toBeTruthy());
it('=> includes #808000', () => expect(names.includes('#808000')).toBeTruthy());
it('=> includes #6B8E23', () => expect(names.includes('#6B8E23')).toBeTruthy());
it('=> includes #FFA500', () => expect(names.includes('#FFA500')).toBeTruthy());
it('=> includes #FF4500', () => expect(names.includes('#FF4500')).toBeTruthy());
it('=> includes #DA70D6', () => expect(names.includes('#DA70D6')).toBeTruthy());
it('=> includes #EEE8AA', () => expect(names.includes('#EEE8AA')).toBeTruthy());
it('=> includes #98FB98', () => expect(names.includes('#98FB98')).toBeTruthy());
it('=> includes #AFEEEE', () => expect(names.includes('#AFEEEE')).toBeTruthy());
it('=> includes #DB7093', () => expect(names.includes('#DB7093')).toBeTruthy());
it('=> includes #FFEFD5', () => expect(names.includes('#FFEFD5')).toBeTruthy());
it('=> includes #FFDAB9', () => expect(names.includes('#FFDAB9')).toBeTruthy());
it('=> includes #CD853F', () => expect(names.includes('#CD853F')).toBeTruthy());
it('=> includes #FFC0CB', () => expect(names.includes('#FFC0CB')).toBeTruthy());
it('=> includes #DDA0DD', () => expect(names.includes('#DDA0DD')).toBeTruthy());
it('=> includes #B0E0E6', () => expect(names.includes('#B0E0E6')).toBeTruthy());
it('=> includes #800080', () => expect(names.includes('#800080')).toBeTruthy());
it('=> includes #663399', () => expect(names.includes('#663399')).toBeTruthy());
it('=> includes #FF0000', () => expect(names.includes('#FF0000')).toBeTruthy());
it('=> includes #BC8F8F', () => expect(names.includes('#BC8F8F')).toBeTruthy());
it('=> includes #4169E1', () => expect(names.includes('#4169E1')).toBeTruthy());
it('=> includes #8B4513', () => expect(names.includes('#8B4513')).toBeTruthy());
it('=> includes #FA8072', () => expect(names.includes('#FA8072')).toBeTruthy());
it('=> includes #F4A460', () => expect(names.includes('#F4A460')).toBeTruthy());
it('=> includes #2E8B57', () => expect(names.includes('#2E8B57')).toBeTruthy());
it('=> includes #FFF5EE', () => expect(names.includes('#FFF5EE')).toBeTruthy());
it('=> includes #A0522D', () => expect(names.includes('#A0522D')).toBeTruthy());
it('=> includes #C0C0C0', () => expect(names.includes('#C0C0C0')).toBeTruthy());
it('=> includes #87CEEB', () => expect(names.includes('#87CEEB')).toBeTruthy());
it('=> includes #6A5ACD', () => expect(names.includes('#6A5ACD')).toBeTruthy());
it('=> includes #708090', () => expect(names.includes('#708090')).toBeTruthy());
it('=> includes #708090', () => expect(names.includes('#708090')).toBeTruthy());
it('=> includes #FFFAFA', () => expect(names.includes('#FFFAFA')).toBeTruthy());
it('=> includes #00FF7F', () => expect(names.includes('#00FF7F')).toBeTruthy());
it('=> includes #4682B4', () => expect(names.includes('#4682B4')).toBeTruthy());
it('=> includes #D2B48C', () => expect(names.includes('#D2B48C')).toBeTruthy());
it('=> includes #008080', () => expect(names.includes('#008080')).toBeTruthy());
it('=> includes #D8BFD8', () => expect(names.includes('#D8BFD8')).toBeTruthy());
it('=> includes #FF6347', () => expect(names.includes('#FF6347')).toBeTruthy());
it('=> includes #40E0D0', () => expect(names.includes('#40E0D0')).toBeTruthy());
it('=> includes #EE82EE', () => expect(names.includes('#EE82EE')).toBeTruthy());
it('=> includes #F5DEB3', () => expect(names.includes('#F5DEB3')).toBeTruthy());
it('=> includes #FFFFFF', () => expect(names.includes('#FFFFFF')).toBeTruthy());
it('=> includes #F5F5F5', () => expect(names.includes('#F5F5F5')).toBeTruthy());
it('=> includes #FFFF00', () => expect(names.includes('#FFFF00')).toBeTruthy());
it('=> includes #9ACD32', () => expect(names.includes('#9ACD32')).toBeTruthy());


it('=> #F0F8FF index(0)', () => expect(names.indexOf('#F0F8FF')).toEqual(0));
it('=> #FAEBD7 index(1)', () => expect(names.indexOf('#FAEBD7')).toEqual(1));
it('=> #00FFFF index(2)', () => expect(names.indexOf('#00FFFF')).toEqual(2));
it('=> #7FFFD4 index(3)', () => expect(names.indexOf('#7FFFD4')).toEqual(3));
it('=> #F0FFFF index(4)', () => expect(names.indexOf('#F0FFFF')).toEqual(4));
it('=> #F5F5DC index(5)', () => expect(names.indexOf('#F5F5DC')).toEqual(5));
it('=> #FFE4C4 index(6)', () => expect(names.indexOf('#FFE4C4')).toEqual(6));
it('=> #9ACD32 index(147)', () => expect(names.indexOf('#9ACD32')).toEqual(147));

it('=> aliceblue -> #F0F8FF', async () => expect(names[colors.indexOf('aliceblue')]).toEqual('#F0F8FF'));
it('=> antiquewhite -> #FAEBD7', async () => expect(names[colors.indexOf('antiquewhite')]).toEqual('#FAEBD7'));
it('=> aqua -> #00FFFF', async () => expect(names[colors.indexOf('aqua')]).toEqual('#00FFFF'));
it('=> aquamarine -> #7FFFD4', async () => expect(names[colors.indexOf('aquamarine')]).toEqual('#7FFFD4'));
it('=> azure -> #F0FFFF', async () => expect(names[colors.indexOf('azure')]).toEqual('#F0FFFF'));
it('=> beige -> #F5F5DC', async () => expect(names[colors.indexOf('beige')]).toEqual('#F5F5DC'));
it('=> bisque -> #FFE4C4', async () => expect(names[colors.indexOf('bisque')]).toEqual('#FFE4C4'));
it('=> black -> #000000', async () => expect(names[colors.indexOf('black')]).toEqual('#000000'));
it('=> blanchedalmond -> #FFEBCD', async () => expect(names[colors.indexOf('blanchedalmond')]).toEqual('#FFEBCD'));
it('=> blue -> #0000FF', async () => expect(names[colors.indexOf('blue')]).toEqual('#0000FF'));
it('=> blueviolet -> #8A2BE2', async () => expect(names[colors.indexOf('blueviolet')]).toEqual('#8A2BE2'));
it('=> brown -> #A52A2A', async () => expect(names[colors.indexOf('brown')]).toEqual('#A52A2A'));
it('=> burlywood -> #DEB887', async () => expect(names[colors.indexOf('burlywood')]).toEqual('#DEB887'));
it('=> cadetblue -> #5F9EA0', async () => expect(names[colors.indexOf('cadetblue')]).toEqual('#5F9EA0'));
it('=> chartreuse -> #7FFF00', async () => expect(names[colors.indexOf('chartreuse')]).toEqual('#7FFF00'));
it('=> chocolate -> #D2691E', async () => expect(names[colors.indexOf('chocolate')]).toEqual('#D2691E'));
it('=> coral -> #FF7F50', async () => expect(names[colors.indexOf('coral')]).toEqual('#FF7F50'));
it('=> cornflowerblue -> #6495ED', async () => expect(names[colors.indexOf('cornflowerblue')]).toEqual('#6495ED'));
it('=> cornsilk -> #FFF8DC', async () => expect(names[colors.indexOf('cornsilk')]).toEqual('#FFF8DC'));
it('=> crimson -> #DC143C', async () => expect(names[colors.indexOf('crimson')]).toEqual('#DC143C'));
it('=> cyan -> #00FFFF', async () => expect(names[colors.indexOf('cyan')]).toEqual('#00FFFF'));
it('=> darkblue -> #00008B', async () => expect(names[colors.indexOf('darkblue')]).toEqual('#00008B'));
it('=> darkcyan -> #008B8B', async () => expect(names[colors.indexOf('darkcyan')]).toEqual('#008B8B'));
it('=> darkgoldenrod -> #B8860B', async () => expect(names[colors.indexOf('darkgoldenrod')]).toEqual('#B8860B'));
it('=> darkgray -> #A9A9A9', async () => expect(names[colors.indexOf('darkgray')]).toEqual('#A9A9A9'));
it('=> darkgreen -> #006400', async () => expect(names[colors.indexOf('darkgreen')]).toEqual('#006400'));
it('=> darkgrey -> #A9A9A9', async () => expect(names[colors.indexOf('darkgrey')]).toEqual('#A9A9A9'));
it('=> darkkhaki -> #BDB76B', async () => expect(names[colors.indexOf('darkkhaki')]).toEqual('#BDB76B'));
it('=> darkmagenta -> #8B008B', async () => expect(names[colors.indexOf('darkmagenta')]).toEqual('#8B008B'));
it('=> darkolivegreen -> #556B2F', async () => expect(names[colors.indexOf('darkolivegreen')]).toEqual('#556B2F'));
it('=> darkorange -> #FF8C00', async () => expect(names[colors.indexOf('darkorange')]).toEqual('#FF8C00'));
it('=> darkorchid -> #9932CC', async () => expect(names[colors.indexOf('darkorchid')]).toEqual('#9932CC'));
it('=> darkred -> #8B0000', async () => expect(names[colors.indexOf('darkred')]).toEqual('#8B0000'));
it('=> darksalmon -> #E9967A', async () => expect(names[colors.indexOf('darksalmon')]).toEqual('#E9967A'));
it('=> darkseagreen -> #8FBC8F', async () => expect(names[colors.indexOf('darkseagreen')]).toEqual('#8FBC8F'));
it('=> darkslateblue -> #483D8B', async () => expect(names[colors.indexOf('darkslateblue')]).toEqual('#483D8B'));
it('=> darkslategray -> #2F4F4F', async () => expect(names[colors.indexOf('darkslategray')]).toEqual('#2F4F4F'));
it('=> darkslategrey -> #2F4F4F', async () => expect(names[colors.indexOf('darkslategrey')]).toEqual('#2F4F4F'));
it('=> darkturquoise -> #00CED1', async () => expect(names[colors.indexOf('darkturquoise')]).toEqual('#00CED1'));
it('=> darkviolet -> #9400D3', async () => expect(names[colors.indexOf('darkviolet')]).toEqual('#9400D3'));
it('=> deeppink -> #FF1493', async () => expect(names[colors.indexOf('deeppink')]).toEqual('#FF1493'));
it('=> deepskyblue -> #00BFFF', async () => expect(names[colors.indexOf('deepskyblue')]).toEqual('#00BFFF'));
it('=> dimgray -> #696969', async () => expect(names[colors.indexOf('dimgray')]).toEqual('#696969'));
it('=> dimgrey -> #696969', async () => expect(names[colors.indexOf('dimgrey')]).toEqual('#696969'));
it('=> dodgerblue -> #1E90FF', async () => expect(names[colors.indexOf('dodgerblue')]).toEqual('#1E90FF'));
it('=> firebrick -> #B22222', async () => expect(names[colors.indexOf('firebrick')]).toEqual('#B22222'));
it('=> floralwhite -> #FFFAF0', async () => expect(names[colors.indexOf('floralwhite')]).toEqual('#FFFAF0'));
it('=> forestgreen -> #228B22', async () => expect(names[colors.indexOf('forestgreen')]).toEqual('#228B22'));
it('=> fuchsia -> #FF00FF', async () => expect(names[colors.indexOf('fuchsia')]).toEqual('#FF00FF'));
it('=> gainsboro -> #DCDCDC', async () => expect(names[colors.indexOf('gainsboro')]).toEqual('#DCDCDC'));
it('=> ghostwhite -> #F8F8FF', async () => expect(names[colors.indexOf('ghostwhite')]).toEqual('#F8F8FF'));
it('=> gold -> #FFD700', async () => expect(names[colors.indexOf('gold')]).toEqual('#FFD700'));
it('=> goldenrod -> #DAA520', async () => expect(names[colors.indexOf('goldenrod')]).toEqual('#DAA520'));
it('=> gray -> #808080', async () => expect(names[colors.indexOf('gray')]).toEqual('#808080'));
it('=> green -> #008000', async () => expect(names[colors.indexOf('green')]).toEqual('#008000'));
it('=> greenyellow -> #ADFF2F', async () => expect(names[colors.indexOf('greenyellow')]).toEqual('#ADFF2F'));
it('=> grey -> #808080', async () => expect(names[colors.indexOf('grey')]).toEqual('#808080'));
it('=> honeydew -> #F0FFF0', async () => expect(names[colors.indexOf('honeydew')]).toEqual('#F0FFF0'));
it('=> hotpink -> #FF69B4', async () => expect(names[colors.indexOf('hotpink')]).toEqual('#FF69B4'));
it('=> indianred -> #CD5C5C', async () => expect(names[colors.indexOf('indianred')]).toEqual('#CD5C5C'));
it('=> indigo -> #4B0082', async () => expect(names[colors.indexOf('indigo')]).toEqual('#4B0082'));
it('=> ivory -> #FFFFF0', async () => expect(names[colors.indexOf('ivory')]).toEqual('#FFFFF0'));
it('=> khaki -> #F0E68C', async () => expect(names[colors.indexOf('khaki')]).toEqual('#F0E68C'));
it('=> lavender -> #E6E6FA', async () => expect(names[colors.indexOf('lavender')]).toEqual('#E6E6FA'));
it('=> lavenderblush -> #FFF0F5', async () => expect(names[colors.indexOf('lavenderblush')]).toEqual('#FFF0F5'));
it('=> lawngreen -> #7CFC00', async () => expect(names[colors.indexOf('lawngreen')]).toEqual('#7CFC00'));
it('=> lemonchiffon -> #FFFACD', async () => expect(names[colors.indexOf('lemonchiffon')]).toEqual('#FFFACD'));
it('=> lightblue -> #ADD8E6', async () => expect(names[colors.indexOf('lightblue')]).toEqual('#ADD8E6'));
it('=> lightcoral -> #F08080', async () => expect(names[colors.indexOf('lightcoral')]).toEqual('#F08080'));
it('=> lightcyan -> #E0FFFF', async () => expect(names[colors.indexOf('lightcyan')]).toEqual('#E0FFFF'));
it('=> lightgoldenrodyellow -> #FAFAD2', async () => expect(names[colors.indexOf('lightgoldenrodyellow')]).toEqual('#FAFAD2'));
it('=> lightgray -> #D3D3D3', async () => expect(names[colors.indexOf('lightgray')]).toEqual('#D3D3D3'));
it('=> lightgreen -> #90EE90', async () => expect(names[colors.indexOf('lightgreen')]).toEqual('#90EE90'));
it('=> lightgrey -> #D3D3D3', async () => expect(names[colors.indexOf('lightgrey')]).toEqual('#D3D3D3'));
it('=> lightpink -> #FFB6C1', async () => expect(names[colors.indexOf('lightpink')]).toEqual('#FFB6C1'));
it('=> lightsalmon -> #FFA07A', async () => expect(names[colors.indexOf('lightsalmon')]).toEqual('#FFA07A'));
it('=> lightseagreen -> #20B2AA', async () => expect(names[colors.indexOf('lightseagreen')]).toEqual('#20B2AA'));
it('=> lightskyblue -> #87CEFA', async () => expect(names[colors.indexOf('lightskyblue')]).toEqual('#87CEFA'));
it('=> lightslategray -> #778899', async () => expect(names[colors.indexOf('lightslategray')]).toEqual('#778899'));
it('=> lightslategrey -> #778899', async () => expect(names[colors.indexOf('lightslategrey')]).toEqual('#778899'));
it('=> lightsteelblue -> #B0C4DE', async () => expect(names[colors.indexOf('lightsteelblue')]).toEqual('#B0C4DE'));
it('=> lightyellow -> #FFFFE0', async () => expect(names[colors.indexOf('lightyellow')]).toEqual('#FFFFE0'));
it('=> lime -> #00FF00', async () => expect(names[colors.indexOf('lime')]).toEqual('#00FF00'));
it('=> limegreen -> #32CD32', async () => expect(names[colors.indexOf('limegreen')]).toEqual('#32CD32'));
it('=> linen -> #FAF0E6', async () => expect(names[colors.indexOf('linen')]).toEqual('#FAF0E6'));
it('=> magenta -> #FF00FF', async () => expect(names[colors.indexOf('magenta')]).toEqual('#FF00FF'));
it('=> maroon -> #800000', async () => expect(names[colors.indexOf('maroon')]).toEqual('#800000'));
it('=> mediumaquamarine -> #66CDAA', async () => expect(names[colors.indexOf('mediumaquamarine')]).toEqual('#66CDAA'));
it('=> mediumblue -> #0000CD', async () => expect(names[colors.indexOf('mediumblue')]).toEqual('#0000CD'));
it('=> mediumorchid -> #BA55D3', async () => expect(names[colors.indexOf('mediumorchid')]).toEqual('#BA55D3'));
it('=> mediumpurple -> #9370DB', async () => expect(names[colors.indexOf('mediumpurple')]).toEqual('#9370DB'));
it('=> mediumseagreen -> #3CB371', async () => expect(names[colors.indexOf('mediumseagreen')]).toEqual('#3CB371'));
it('=> mediumslateblue -> #7B68EE', async () => expect(names[colors.indexOf('mediumslateblue')]).toEqual('#7B68EE'));
it('=> mediumspringgreen -> #00FA9A', async () => expect(names[colors.indexOf('mediumspringgreen')]).toEqual('#00FA9A'));
it('=> mediumturquoise -> #48D1CC', async () => expect(names[colors.indexOf('mediumturquoise')]).toEqual('#48D1CC'));
it('=> mediumvioletred -> #C71585', async () => expect(names[colors.indexOf('mediumvioletred')]).toEqual('#C71585'));
it('=> midnightblue -> #191970', async () => expect(names[colors.indexOf('midnightblue')]).toEqual('#191970'));
it('=> mintcream -> #F5FFFA', async () => expect(names[colors.indexOf('mintcream')]).toEqual('#F5FFFA'));
it('=> mistyrose -> #FFE4E1', async () => expect(names[colors.indexOf('mistyrose')]).toEqual('#FFE4E1'));
it('=> moccasin -> #FFE4B5', async () => expect(names[colors.indexOf('moccasin')]).toEqual('#FFE4B5'));
it('=> navajowhite -> #FFDEAD', async () => expect(names[colors.indexOf('navajowhite')]).toEqual('#FFDEAD'));
it('=> navy -> #000080', async () => expect(names[colors.indexOf('navy')]).toEqual('#000080'));
it('=> oldlace -> #FDF5E6', async () => expect(names[colors.indexOf('oldlace')]).toEqual('#FDF5E6'));
it('=> olive -> #808000', async () => expect(names[colors.indexOf('olive')]).toEqual('#808000'));
it('=> olivedrab -> #6B8E23', async () => expect(names[colors.indexOf('olivedrab')]).toEqual('#6B8E23'));
it('=> orange -> #FFA500', async () => expect(names[colors.indexOf('orange')]).toEqual('#FFA500'));
it('=> orangered -> #FF4500', async () => expect(names[colors.indexOf('orangered')]).toEqual('#FF4500'));
it('=> orchid -> #DA70D6', async () => expect(names[colors.indexOf('orchid')]).toEqual('#DA70D6'));
it('=> palegoldenrod -> #EEE8AA', async () => expect(names[colors.indexOf('palegoldenrod')]).toEqual('#EEE8AA'));
it('=> palegreen -> #98FB98', async () => expect(names[colors.indexOf('palegreen')]).toEqual('#98FB98'));
it('=> paleturquoise -> #AFEEEE', async () => expect(names[colors.indexOf('paleturquoise')]).toEqual('#AFEEEE'));
it('=> palevioletred -> #DB7093', async () => expect(names[colors.indexOf('palevioletred')]).toEqual('#DB7093'));
it('=> papayawhip -> #FFEFD5', async () => expect(names[colors.indexOf('papayawhip')]).toEqual('#FFEFD5'));
it('=> peachpuff -> #FFDAB9', async () => expect(names[colors.indexOf('peachpuff')]).toEqual('#FFDAB9'));
it('=> peru -> #CD853F', async () => expect(names[colors.indexOf('peru')]).toEqual('#CD853F'));
it('=> pink -> #FFC0CB', async () => expect(names[colors.indexOf('pink')]).toEqual('#FFC0CB'));
it('=> plum -> #DDA0DD', async () => expect(names[colors.indexOf('plum')]).toEqual('#DDA0DD'));
it('=> powderblue -> #B0E0E6', async () => expect(names[colors.indexOf('powderblue')]).toEqual('#B0E0E6'));
it('=> purple -> #800080', async () => expect(names[colors.indexOf('purple')]).toEqual('#800080'));
it('=> rebeccapurple -> #663399', async () => expect(names[colors.indexOf('rebeccapurple')]).toEqual('#663399'));
it('=> red -> #FF0000', async () => expect(names[colors.indexOf('red')]).toEqual('#FF0000'));
it('=> rosybrown -> #BC8F8F', async () => expect(names[colors.indexOf('rosybrown')]).toEqual('#BC8F8F'));
it('=> royalblue -> #4169E1', async () => expect(names[colors.indexOf('royalblue')]).toEqual('#4169E1'));
it('=> saddlebrown -> #8B4513', async () => expect(names[colors.indexOf('saddlebrown')]).toEqual('#8B4513'));
it('=> salmon -> #FA8072', async () => expect(names[colors.indexOf('salmon')]).toEqual('#FA8072'));
it('=> sandybrown -> #F4A460', async () => expect(names[colors.indexOf('sandybrown')]).toEqual('#F4A460'));
it('=> seagreen -> #2E8B57', async () => expect(names[colors.indexOf('seagreen')]).toEqual('#2E8B57'));
it('=> seashell -> #FFF5EE', async () => expect(names[colors.indexOf('seashell')]).toEqual('#FFF5EE'));
it('=> sienna -> #A0522D', async () => expect(names[colors.indexOf('sienna')]).toEqual('#A0522D'));
it('=> silver -> #C0C0C0', async () => expect(names[colors.indexOf('silver')]).toEqual('#C0C0C0'));
it('=> skyblue -> #87CEEB', async () => expect(names[colors.indexOf('skyblue')]).toEqual('#87CEEB'));
it('=> slateblue -> #6A5ACD', async () => expect(names[colors.indexOf('slateblue')]).toEqual('#6A5ACD'));
it('=> slategray -> #708090', async () => expect(names[colors.indexOf('slategray')]).toEqual('#708090'));
it('=> slategrey -> #708090', async () => expect(names[colors.indexOf('slategrey')]).toEqual('#708090'));
it('=> snow -> #FFFAFA', async () => expect(names[colors.indexOf('snow')]).toEqual('#FFFAFA'));
it('=> springgreen -> #00FF7F', async () => expect(names[colors.indexOf('springgreen')]).toEqual('#00FF7F'));
it('=> steelblue -> #4682B4', async () => expect(names[colors.indexOf('steelblue')]).toEqual('#4682B4'));
it('=> tan -> #D2B48C', async () => expect(names[colors.indexOf('tan')]).toEqual('#D2B48C'));
it('=> teal -> #008080', async () => expect(names[colors.indexOf('teal')]).toEqual('#008080'));
it('=> thistle -> #D8BFD8', async () => expect(names[colors.indexOf('thistle')]).toEqual('#D8BFD8'));
it('=> tomato -> #FF6347', async () => expect(names[colors.indexOf('tomato')]).toEqual('#FF6347'));
it('=> turquoise -> #40E0D0', async () => expect(names[colors.indexOf('turquoise')]).toEqual('#40E0D0'));
it('=> violet -> #EE82EE', async () => expect(names[colors.indexOf('violet')]).toEqual('#EE82EE'));
it('=> wheat -> #F5DEB3', async () => expect(names[colors.indexOf('wheat')]).toEqual('#F5DEB3'));
it('=> white -> #FFFFFF', async () => expect(names[colors.indexOf('white')]).toEqual('#FFFFFF'));
it('=> whitesmoke -> #F5F5F5', async () => expect(names[colors.indexOf('whitesmoke')]).toEqual('#F5F5F5'));
it('=> yellow -> #FFFF00', async () => expect(names[colors.indexOf('yellow')]).toEqual('#FFFF00'));
it('=> yellowgreen -> #9ACD32', async () => expect(names[colors.indexOf('yellowgreen')]).toEqual('#9ACD32'));